apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hermes.fullname" . }}
  labels:
    {{- include "hermes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "hermes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hermes.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "hermes.serviceAccountName" . }}
      terminationGracePeriodSeconds: 30
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hermes
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --addr={{ .Values.dataplane.addr }}
            - --ingress-class={{ .Values.controller.ingressClass }}
            - --metrics-addr={{ .Values.controller.metricsAddr }}
            {{- if .Values.controller.watchNamespace }}
            - --watch-namespace={{ .Values.controller.watchNamespace }}
            {{- end }}
            {{- if .Values.controller.statusHostname }}
            - --status-hostname={{ .Values.controller.statusHostname }}
            {{- end }}
            {{- if .Values.controller.statusAddress }}
            - --status-address={{ .Values.controller.statusAddress }}
            {{- end }}
            {{- if .Values.controller.enableGatewayAPI }}
            - --enable-gateway-api
            {{- end }}
            {{- if .Values.controller.enableHTTPProxy }}
            - --enable-httpproxy
            {{- end }}
            {{- if .Values.controller.leaderElect }}
            - --leader-elect
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 8081
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
